version: "3"

services:

  server:
    image: "asu:latest"
    build:
      context: ./
      dockerfile: Containerfile
    restart: always
    environment:
      - REDIS_URL=${REDIS_URL}
    volumes:
      - .env:/app/.env
      - $PUBLIC_PATH:$PUBLIC_PATH:rw
    ports:
      - "8000:8000"

  worker:
    image: "asu:latest"
    build:
      context: ./
      dockerfile: Containerfile
    restart: always
    command: poetry run rq worker
    environment:
      - REDIS_URL=${REDIS_URL}
      - CONTAINER_HOST=unix://$CONTAINER_SOCK
    volumes:
      - .env:/app/.env
      - $PUBLIC_PATH:$PUBLIC_PATH:rw
      - $CONTAINER_SOCK:$CONTAINER_SOCK:rw